outputs: ''
prepare: ''
run: '|'
echo: '""'
output: trivy-report.json
path: .
password: ${{ secrets.GITHUB_TOKEN }}
workflow_dispatch: ''
permissions: ''
sast: ''
image_tag: ${{ steps.vars.outputs.image_tag }}
id: vars
if: github.event_name != 'pull_request'
needs: '[prepare, container_scanning]'
IMAGE_TAG: '"${GITHUB_RUN_ID}"'
format: table
count: $(jq -r --arg s "$sev" '[.Results[]? | .Vulnerabilities // [] | .[] | select(.Severity
  == $s)] | length' trivy-report.json)
exit-code: '1'
branches: '[main, master]'
packages: write
steps: ''
'-': 'name: Push image'
done: ''
push: ''
lint: ''
shell: bash
contents: read
image-ref: '"${{ env.PROJECT_NAME }}:${{ needs.prepare.outputs.image_tag }}"'
name: built-image
container_scanning: ''
for: sev in CRITICAL HIGH MEDIUM LOW UNKNOWN; do
PROJECT_NAME: securityaudit
docker: push "${{ needs.prepare.outputs.ghcr_image }}"
printf: '[B@183117b4'
total: $((total + count))
cat: gl-sast-report.json
sudo: apt-get install -y jq
GHCR_IMAGE: '"ghcr.io/${OWNER_LC}/${PROJECT_NAME}:${IMAGE_TAG}"'
'on': ''
severity: CRITICAL
'```': ''
registry: ghcr.io
pull_request: ''
jobs: ''
ghcr_image: ${{ steps.vars.outputs.ghcr_image }}
OWNER_LC: '"$(echo "${GITHUB_REPOSITORY_OWNER}" | tr ''[:upper:]'' ''[:lower:]'')"'
env: ''
with: ''
runs-on: ubuntu-latest
build: ''
uses: docker/login-action@v3
username: ${{ github.actor }}
